name: Build SVG to STL Converter

on:
  push:
    tags:
      - '*' # При публикации тега с версией (например v1.0.0)
  workflow_dispatch: # Для ручного запуска

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04  # Используем более старую версию Ubuntu для максимальной совместимости
            artifact_name: svg2stl-linux
            asset_name: svg2stl-linux
          - os: windows-latest
            artifact_name: svg2stl-windows.exe
            asset_name: svg2stl-windows
          - os: macos-latest
            artifact_name: svg2stl-macos
            asset_name: svg2stl-macos

    steps:
    - name: Checkout код
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'  # Используем Python 3.8 для лучшей совместимости
        cache: 'pip'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # Дополнительная установка Nuitka для Windows
    - name: Установка Nuitka для Windows
      if: matrix.os == 'windows-latest'
      run: |
        pip install nuitka
        pip install ordered-set zstandard

    - name: Создание файлов метаданных для Windows
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        # Создание файла версии для встраивания в Windows PE
        cat > version_info.txt << EOF
        CompanyName: SVG to STL Converter
        FileDescription: SVG to STL Converter Tool
        FileVersion: 1.0.0
        InternalName: svg2stl
        LegalCopyright: MIT License
        OriginalFilename: svg2stl.exe
        ProductName: SVG to STL Converter
        ProductVersion: 1.0.0
        EOF

    - name: Сборка с PyInstaller для Linux
      if: matrix.os == 'ubuntu-20.04'
      run: |
        # Используем специальные опции для создания максимально портативного бинарника
        pyinstaller --onefile --clean --name ${{ matrix.artifact_name }} \
          --hidden-import=PIL._tkinter_finder \
          --exclude-module=tcl \
          --exclude-module=tk \
          --exclude-module=Tkinter \
          --exclude-module=_tkinter \
          svg2stl.py

    - name: Сборка с PyInstaller для macOS
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --name ${{ matrix.artifact_name }} svg2stl.py

    - name: Сборка с Nuitka для Windows
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        :: Используем Nuitka вместо PyInstaller для сборки Windows
        python -m nuitka --mingw64 --standalone --onefile --assume-yes-for-downloads ^
          --company-name="SVG to STL Converter" ^
          --product-name="SVG to STL Converter" ^
          --file-version="1.0.0" ^
          --product-version="1.0.0" ^
          --file-description="SVG to STL Converter Tool" ^
          --copyright="MIT License" ^
          --include-package=numpy ^
          --include-package=cairosvg ^
          --include-package=PIL ^
          --include-package=stl ^
          --include-package=tqdm ^
          --windows-disable-console ^
          --output-filename=${{ matrix.artifact_name }} ^
          svg2stl.py
        
        :: Перемещаем исполняемый файл в dist
        mkdir dist
        move ${{ matrix.artifact_name }} dist\

    - name: Загрузить артефакты сборки
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.artifact_name }}*

  release:
    name: Создание релиза
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
    - name: Checkout код
      uses: actions/checkout@v4
      
    - name: Создание релиза
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
      
    - name: Скачать все артефакты
      uses: actions/download-artifact@v4
      
    - name: Загрузить артефакты в релиз
      uses: softprops/action-gh-release@v1
      with:
        files: |
          svg2stl-linux/svg2stl-linux
          svg2stl-windows/svg2stl-windows.exe
          svg2stl-macos/svg2stl-macos 